name: Sync Supabase Facts to Pinecone

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:      # eseguibile anche manualmente

jobs:
  sync-facts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          PINECONE_REGION: ${{ secrets.PINECONE_REGION }}
          PINECONE_CLOUD: ${{ secrets.PINECONE_CLOUD }}
        run: python scripts/sync_facts_to_memory.py
